// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TopStories;

namespace TopStories.Migrations
{
    [DbContext(typeof(APIConsumerContext))]
    partial class APIConsumerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("TopStories.StoryContext", b =>
                {
                    b.Property<string>("key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("byline")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("published_date")
                        .HasColumnType("TEXT");

                    b.Property<string>("section")
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.HasKey("key");

                    b.ToTable("Stories");
                });
#pragma warning restore 612, 618
        }
    }
}
